no-task add tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,2 +1,60 @@
-# The Docker image that will be used to build your app
-image: node:lts
+image: registry.gitlab.nxs360.com/docker/php:8.1-cli
+
+stages:
+  - validation
+  - deploy
+  - post-test
+
+composer:validate:
+  stage: validation
+  script:
+    - composer validate
+    - composer install
+    - composer cs-check
+    - composer md-check
+    - composer test
+  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
+  artifacts:
+    expire_in: 30 days
+    paths:
+      - tests/_output/
+    reports:
+      coverage_report:
+        coverage_format: cobertura
+        path: tests/_output/cobertura.xml
+      junit: tests/_output/coverage.xml
+
+pages:
+  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/ruby:2.7
+  stage: deploy
+  script:
+    - "mv tests/_output/coverage/ public/"
+  artifacts:
+    expire_in: 30 days
+    paths:
+      - public
+  only:
+    - master
+
+deploy:composer:
+  stage: deploy
+  script:
+    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
+    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
+    - code=$(echo "$response" | tail -n 1)
+    - body=$(echo "$response" | head -n 1)
+    # Output state information
+    - |
+      if [ $code -eq 201 ]; then
+        echo "Package created - Code $code - $body";
+      else
+        echo "Could not create package - Code $code - $body";
+        exit 1
+      fi
+  variables:
+    URL: "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
+  rules:
+    - if: $CI_MERGE_REQUEST_ID
+      when: never
+    - if: $CI_COMMIT_TAG =~ /^?[0-9]+[.][0-9]+([.][0-9]+)?$/
+
